# Generated by Django 5.2.5 on 2025-08-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("product.enhanced", "Product Enhanced"),
                            (
                                "product.enhancement_failed",
                                "Product Enhancement Failed",
                            ),
                            ("product.published", "Product Published"),
                            ("product.publish_failed", "Product Publish Failed"),
                            ("workflow.completed", "Workflow Completed"),
                            ("workflow.error", "Workflow Error"),
                            ("canvas.workflow.started", "Canvas Workflow Started"),
                            ("canvas.workflow.error", "Canvas Workflow Error"),
                            ("marketplace.publish.retry", "Marketplace Publish Retry"),
                            (
                                "webhook.max_retries_exceeded",
                                "Webhook Max Retries Exceeded",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField()),
                ("webhook_url", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
