version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: multimarket_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A src.config worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0

volumes:
  postgres_data: